// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1g14Zo1V3vODLfWGpB1ooaLqzb4bJnSI',
    appId: '1:483776769250:web:6033842dee8ed532e202bb',
    messagingSenderId: '483776769250',
    projectId: 'wacamaya-sports',
    authDomain: 'wacamaya-sports.firebaseapp.com',
    storageBucket: 'wacamaya-sports.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTskoJ9qAuIA8bArPvkkRVptHXaoaNzvY',
    appId: '1:483776769250:android:fa215784753f7b09e202bb',
    messagingSenderId: '483776769250',
    projectId: 'wacamaya-sports',
    storageBucket: 'wacamaya-sports.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo_WcZ3siZ4XlFKEKEQrjzveFiDxQkubs',
    appId: '1:483776769250:ios:6fc01955f5bff23fe202bb',
    messagingSenderId: '483776769250',
    projectId: 'wacamaya-sports',
    storageBucket: 'wacamaya-sports.firebasestorage.app',
    androidClientId: '483776769250-ikrbbscfi3c3ghrhi8fjtf41fm1at9vn.apps.googleusercontent.com',
    iosClientId: '483776769250-1sc70gfpkqf65qq9r0ftb619bh7gdgm0.apps.googleusercontent.com',
    iosBundleId: 'com.example.wacamayaSports',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo_WcZ3siZ4XlFKEKEQrjzveFiDxQkubs',
    appId: '1:483776769250:ios:6fc01955f5bff23fe202bb',
    messagingSenderId: '483776769250',
    projectId: 'wacamaya-sports',
    storageBucket: 'wacamaya-sports.firebasestorage.app',
    androidClientId: '483776769250-ikrbbscfi3c3ghrhi8fjtf41fm1at9vn.apps.googleusercontent.com',
    iosClientId: '483776769250-1sc70gfpkqf65qq9r0ftb619bh7gdgm0.apps.googleusercontent.com',
    iosBundleId: 'com.example.wacamayaSports',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1g14Zo1V3vODLfWGpB1ooaLqzb4bJnSI',
    appId: '1:483776769250:web:f439235ca026383fe202bb',
    messagingSenderId: '483776769250',
    projectId: 'wacamaya-sports',
    authDomain: 'wacamaya-sports.firebaseapp.com',
    storageBucket: 'wacamaya-sports.firebasestorage.app',
  );
}
